default_language_version:
  # default language version for each language
  python: python3.8
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-merge-conflict
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.8.0
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    -   id: black
